stages:
  - build
  - deploy
  
image: debian:latest
  

build-job:
  stage: build
  image: docker:latest
  services:
    - docker:18.09.7-dind
  script:
    - ls /builds/Zarby/vtbot/
    - ls /builds/Zarby/vtbot/.git/
    - cd /builds/Zarby/vtbot/
    - echo "Compiling the code..."
    - docker build -t vtbot .
    - echo "Compiling done"

deploy-job:
  stage: deploy
  image: docker:latest
  services:
    - docker:18.09.7-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - echo "Pushing image"
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "Image pushed sucessfully"
