stages:
  - build

build-job:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - echo "Test"
    - echo "Compiling the code..."
    - docker build -t DiscordBot .
    - echo "Compiling done"
