stages:
  - build

image: gitlab/dind

build-job:
  stage: build
  script:
    - echo "Test"
    - apt-get install python3
    - echo "Compiling the code..."
    - docker build -t DiscordBot .
    - echo "Compiling done"
